CREATE TABLE IF NOT EXISTS inscriptos (
  nro INTEGER PRIMARY KEY,
  piloto VARCHAR(255) NOT NULL,
  navegante VARCHAR(255) NOT NULL,
  vehiculo VARCHAR(255) NOT NULL,
  clase VARCHAR(100) NOT NULL,
  nac VARCHAR(50) NOT NULL
);
