CREATE TABLE IF NOT EXISTS tramos (
  pe INTEGER PRIMARY KEY,
  etapa INTEGER NOT NULL,
  desde VARCHAR(255) NOT NULL,
  hasta VARCHAR(255) NOT NULL DEFAULT '',
  kms VARCHAR(20) NOT NULL,
  hora VARCHAR(10) NOT NULL,
  estado VARCHAR(50) NOT NULL
);
