CREATE TABLE IF NOT EXISTS horarios_largada (
  nro INTEGER NOT NULL,
  etapa INTEGER NOT NULL,
  piloto VARCHAR(255) NOT NULL DEFAULT '',
  navegante VARCHAR(255) NOT NULL DEFAULT '',
  vehiculo VARCHAR(255) NOT NULL DEFAULT '',
  clase VARCHAR(100) NOT NULL DEFAULT '',
  nac VARCHAR(50) NOT NULL DEFAULT '',
  hora VARCHAR(10) NOT NULL,
  PRIMARY KEY (nro, etapa)
);

ALTER TABLE horarios_largada
  ADD COLUMN IF NOT EXISTS piloto VARCHAR(255) NOT NULL DEFAULT '';

ALTER TABLE horarios_largada
  ADD COLUMN IF NOT EXISTS navegante VARCHAR(255) NOT NULL DEFAULT '';

ALTER TABLE horarios_largada
  ADD COLUMN IF NOT EXISTS vehiculo VARCHAR(255) NOT NULL DEFAULT '';

ALTER TABLE horarios_largada
  ADD COLUMN IF NOT EXISTS clase VARCHAR(100) NOT NULL DEFAULT '';

ALTER TABLE horarios_largada
  ADD COLUMN IF NOT EXISTS nac VARCHAR(50) NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS horarios_largada_publicados (
  nro INTEGER NOT NULL,
  etapa INTEGER NOT NULL,
  piloto VARCHAR(255) NOT NULL DEFAULT '',
  navegante VARCHAR(255) NOT NULL DEFAULT '',
  vehiculo VARCHAR(255) NOT NULL DEFAULT '',
  clase VARCHAR(100) NOT NULL DEFAULT '',
  nac VARCHAR(50) NOT NULL DEFAULT '',
  hora VARCHAR(10) NOT NULL,
  PRIMARY KEY (nro, etapa)
);
