CREATE TABLE IF NOT EXISTS penalizaciones (
  id_penal INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nro INTEGER NOT NULL,
  peocurrido INTEGER NOT NULL,
  tiempo VARCHAR(20) NOT NULL,
  motivo VARCHAR(255) NOT NULL,
  control VARCHAR(50) NOT NULL
);
