CREATE TABLE IF NOT EXISTS shakedown (
  nro INTEGER PRIMARY KEY,
  hlv1 VARCHAR(20) NOT NULL DEFAULT '',
  tv1 VARCHAR(20) NOT NULL DEFAULT '',
  v1 VARCHAR(20) NOT NULL DEFAULT '',
  hlv2 VARCHAR(20) NOT NULL DEFAULT '',
  tv2 VARCHAR(20) NOT NULL DEFAULT '',
  v2 VARCHAR(20) NOT NULL DEFAULT '',
  hlv3 VARCHAR(20) NOT NULL DEFAULT '',
  tv3 VARCHAR(20) NOT NULL DEFAULT '',
  v3 VARCHAR(20) NOT NULL DEFAULT ''
);
